### ISSUE TITLE
ERROR: E:\workspace dummy\WallBay-master\keystore.properties (The system cannot find the file specified) Open File

### ISSUE THREAD

**Issue by VenkataKrsna** [medyas/Capstone-Project#1]
Hi, error while loading project. can you help me resolve this error?

**Comment by medyas** [comment]
Hi, to build the release apk or bundle you require having a keystore which is missing for you. this can be done using Android Studio: https://developer.android.com/studio/publish/app-signing#generate-key 
After that create a file "keystore.properties" and place :
```
keyAlias KEYALIAS
keyPassword  KEYPASSWORD
storeFile STOREFILE
storePassword STOREPASSWORD
```


which then will be read in the build.gradle file, you will find this code to read and use the generated key to sign the relase apk/bundle.
```

def keystorePropertiesFile = rootProject.file("keystore.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
...
signingConfigs {
        config {
        }
        medyas {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
...
release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.medyas
        }

```
If you want a release apk/bundle i can add it to the repo

**Comment by VenkataKrsna** [comment]
Thank you, now I created keystore.properties file. Now its working
